pipeline:
  on:
    push:
      branches: ["main"]
    mr:
      actions: [opened, synchronized]

  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:debug
      commands:
        - /kaniko/executor --context=dir:///workspace --dockerfile=/workspace/Dockerfile --destination=$REGISTRY/$PROJECT/app:$COMMIT_SHA --insecure --cache=true

    - name: build-test
      image: gcr.io/kaniko-project/executor:debug
      commands:
        - /kaniko/executor --context=dir:///workspace --dockerfile=/workspace/Dockerfile.test --destination=$REGISTRY/$PROJECT/test:$COMMIT_SHA --insecure
      only:
        events: [mr]

  dev_image:
    dockerfile: Dockerfile.dev
